package dev.nikosg.hibernate.example.entity;

import javax.persistence.*;
import java.util.SortedMap;
import java.util.TreeMap;

//Mapping the Collection: SortedMap

// create table IMAGE5 (
// CUSTOMERID bigint not null,
// IMAGEDESCR varchar(255),
// FILENAME varchar(255) not null,
// primary key (CUSTOMERID, FILENAME)
// )

// create table CUSTOMER5 (
// id bigint generated by default as identity,
// EMAIL varchar(255),
// FIRSTNAME varchar(255),
// LASTNAME varchar(255),
// primary key (id)
// )

// Alter table IMAGE5
//  add constraint FKklahf5j3llm7ulsp23kuqra61 foreign key (CUSTOMERID) references CUSTOMER5

@Entity
@Table(name="CUSTOMER5")
public class Customer5 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "FIRSTNAME")
    private String firstName;

    @Column(name = "LASTNAME")
    private String lastName;

    @Column(name = "EMAIL")
    private String email;

    @ElementCollection //this tells Hibernate that we are mapping a collection
    @CollectionTable(
            name = "IMAGE5", //this is the table name
            joinColumns = @JoinColumn(name = "CUSTOMERID"))
    @MapKeyColumn(name = "FILENAME") //this is the key of the Map
    @Column(name = "IMAGEDESCR") //this is the value of the Map
    @OrderBy("FILENAME asc ") //defaults to sort by Map key
    private SortedMap<String, String> images = new TreeMap<>();

    //hibernate requires a no-arg constructor in order to retrieve data
    public Customer5(){

    }

    public Customer5(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    public SortedMap<String, String> getImages() {
        return images;
    }

    @Override
    public String toString() {
        return "Student {" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }

}
