package dev.nikosg.hibernate.example.entity;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

//Mapping the Collection: List

//create table IMAGE2 (
// CUSTOMERID bigint not null,
// FILENAME varchar(255),
// SEQ integer not null,
// primary key (CUSTOMERID, SEQ)
// )

//create table CUSTOMER2 (
// id bigint generated by default as identity,
// EMAIL varchar(255),
// FIRSTNAME varchar(255),
// LASTNAME varchar(255),
// primary key (id)
// )
// Alter table IMAGE2
//  add constraint FKputtakvwkw9a903pbj4iknxol foreign key (CUSTOMERID) references CUSTOMER2

@Entity
@Table(name="CUSTOMER2")
public class Customer2 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "FIRSTNAME")
    private String firstName;

    @Column(name = "LASTNAME")
    private String lastName;

    @Column(name = "EMAIL")
    private String email;

    @ElementCollection //this tells Hibernate that we are mapping a collection
    @CollectionTable(
            name = "IMAGE2", //this is the table name
            joinColumns = @JoinColumn(name = "CUSTOMERID"))
    @OrderColumn(name = "SEQ") //defaults to images_ORDER
    @Column(name = "FILENAME") //defaults to images
    private List<String> images = new ArrayList<>();


    public Customer2(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    public List<String> getImages() {
        return images;
    }

    @Override
    public String toString() {
        return "Student {" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }

}
