package dev.nikosg.hibernate.example.entity;

import javax.persistence.*;

//Mapping Components: Embeddable

//create table CUSTOMER7 (
// id bigint generated by default as identity,
// BILLCITY varchar(255),
// BILLSTREET varchar(255),
// BILLZIP varchar(255),
// EMAIL varchar(255),
// FIRSTNAME varchar(255),
// CITY varchar(255),
// STREET varchar(255),
// ZIPCODE varchar(255),
// LASTNAME varchar(255),
// primary key (id)
// )

//insert into CUSTOMER7 (id, BILLCITY, BILLSTREET, BILLZIP, EMAIL, FIRSTNAME, CITY, STREET, ZIPCODE, LASTNAME)
// values
// (default, ?, ?, ?, ?, ?, ?, ?, ?, ?)

@Entity
@Table(name="CUSTOMER7")
public class Customer7 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "FIRSTNAME")
    private String firstName;

    @Column(name = "LASTNAME")
    private String lastName;

    @Column(name = "EMAIL")
    private String email;

    @Embedded //this is optional annotation. hibernate will infer it because Address class is marked as Embeddable
    private Address homeAddress;

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "street", //this is the java field, not the DB field
                    column = @Column(name = "BILLSTREET")),
            @AttributeOverride(name = "city",
                    column = @Column(name = "BILLCITY")),
            @AttributeOverride(name = "zipcode",
                    column = @Column(name = "BILLZIP"))
    })
    private Address billingAddress;

    public Customer7(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    public Address getHomeAddress() {
        return homeAddress;
    }

    public void setHomeAddress(Address homeAddress) {
        this.homeAddress = homeAddress;
    }

    public Address getBillingAddress() {
        return billingAddress;
    }

    public void setBillingAddress(Address billingAddress) {
        this.billingAddress = billingAddress;
    }

    @Override
    public String toString() {
        return "Student {" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }

}
