package dev.nikosg.hibernate.example.entity;

import javax.persistence.*;

//Mapping the Inheritance: MappedSuperClass Strategy

//create table TEACHER4 (
// id bigint generated by default as identity,
// EMAIL varchar(255),
// FIRSTNAME varchar(255),
// LASTNAME varchar(255),
// SALARY double,
// primary key (id)
// )

//create table STUDENT4 (
// id bigint generated by default as identity,
// EMAIL varchar(255),
// FIRSTNAME varchar(255),
// LASTNAME varchar(255),
// COURSE varchar(255),
// primary key (id)
// )

//Hibernate: insert into STUDENT4 (id, EMAIL, FIRSTNAME, LASTNAME, COURSE) values (default, ?, ?, ?, ?)
//Hibernate: insert into TEACHER4 (id, EMAIL, FIRSTNAME, LASTNAME, SALARY) values (default, ?, ?, ?, ?)

@MappedSuperclass //no need for @Inheritance and @Entity annotations if @MappedSuperclass
public abstract class User4 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "FIRSTNAME")
    private String firstName;

    @Column(name = "LASTNAME")
    private String lastName;

    @Column(name = "EMAIL")
    private String email;

    public User4(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public long getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    @Override
    public String toString() {
        return "User1{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
