package dev.nikosg.hibernate.example.entity;

import javax.persistence.*;

//Mapping the Inheritance: Single Table Strategy

//Table has columns for all fields in inheritance tree

//create table USER1 (
// USERTYPE varchar(31) not null,
// id bigint generated by default as identity,
// EMAIL varchar(255),
// FIRSTNAME varchar(255),
// LASTNAME varchar(255),
// COURSE varchar(255),
// SALARY double,
// primary key (id)
// )


@Entity
@Table(name = "USER1")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE) //map all fields in inheritance tree to a single DB table
@DiscriminatorColumn(name="USERTYPE", discriminatorType = DiscriminatorType.STRING)
public abstract class User1 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "FIRSTNAME")
    private String firstName;

    @Column(name = "LASTNAME")
    private String lastName;

    @Column(name = "EMAIL")
    private String email;

    public User1(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public long getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    @Override
    public String toString() {
        return "User1{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
